import { createElement } from 'lwc';
import Aura_sheet_Q3_lwc from 'c/aura_sheet_Q3_lwc';

describe('c-aura-sheet-q-3-lwc', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-aura-sheet-q-3-lwc', {
            is: Aura_sheet_Q3_lwc
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});