import { createElement } from 'lwc';
import Aura_sheet_lwc_Q6 from 'c/aura_sheet_lwc_Q6';

describe('c-aura-sheet-lwc-q-6', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-aura-sheet-lwc-q-6', {
            is: Aura_sheet_lwc_Q6
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});